package com.nima.dcms.database

import android.content.Context
import io.objectbox.BoxStore




class DataBase {
//    // MyObjectBox is generated by ObjectBox
//    var boxStore: BoxStore = BoxStore.builder()
//        .androidContext(this@YourApp).build()
//    // Listen to all changes to a Box
//    val flow = store.subscribe(TestEntity::class.java).toFlow()

}

object ObjectBox {
    lateinit var store: BoxStore
        private set

//    fun init(context: Context) {
//        store = MyObjectBox.builder()
//            .androidContext(context.applicationContext)
//            .build()
//    }
}
